Homework 2
batrinho/StocksApp pull request #3
Opened 2023-11-04 06:42 UTC by batrinho

2023-11-06 14:05 UTC, Amirzzzhan requested changes

2023-11-06 14:05 UTC, Amirzzzhan commented on StocksApp/AppDelegate.swift
> -        print("Application moved from \(state ?? "Not Running") to \(UIApplication.State.inactive.stringValue): \(#function)")
1 домашканы кетирмеген дурыс)

Егер консольга шыкканы унамай турса, гоу логирование замутим через флаг в info файле. One-to-one кезинде тусиндире алам

2023-11-06 14:05 UTC, Amirzzzhan commented on StocksApp/Controllers/StocksViewController.swift
> +final class StocksViewController: UIViewController, HandleRequestButtonTapDelegate {
для HandleRequestButtonTapDelegate создай extension

2023-11-08 11:44 UTC, Amirzzzhan approved these changes

2023-11-25 07:26 UTC, Amirzzzhan commented on StocksApp/AppDelegate.swift
> -
1 домашканы орнына коймагансын

2023-11-27 11:01 UTC, Amirzzzhan requested changes

2023-11-27 11:01 UTC, Amirzzzhan commented on StocksApp/Modules/Stocks View Controller/Views/StocksTableViewCell.swift
> +    static let identifier = "stocksCell"
забыл что ли как я показывал?)))

https://developer.apple.com/documentation/swift/string/init(describing:)-67ncf

2023-11-27 12:57 UTC, batrinho commented on StocksApp/Modules/Stocks View Controller/Presenter/StocksViewControllerPresenter.swift
> +            filterStocks(with: "")
"" орнына String() деп па?

2023-11-28 09:48 UTC, merged